train_path: "./Caltech256/train.tfrecord"
eval_path: "./Caltech256/eval.tfrecord"
format_spec_path: "./Caltech256/format_spec.pbtxt"
label_map_path: "./Caltech256/label_map.pbtxt"
model_dir: "./models/mobilenet/0001"
learning_rate: 0.0005
num_epochs: 16
batch_size: 64
data_format: "NHWC"
classifier: "mobilenet_v1"
augmentations: {
    flip_horizontal: true
    color_adjustment: true
    translate_vertical_max_px: 3
    translate_horizontal_max_px: 3
    rotate_max_degrees: 8
}