FROM nvcr.io/nvidia/pytorch:21.12-py3
LABEL maintainer="Brad Larson"

#USER root
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove -y && \
    apt-get install -y libgl1-mesa-glx wget ffmpeg

#RUN useradd -D user
#USER user
#WORKDIR /home/user

RUN pip3 install --no-cache-dir \
        opencv-python \
        minio \
        tqdm \
        natsort \
        debugpy \
        path \
        matplotlib \
        torch \
        torchvision \
        tensorboard \
        tensorboardX \
        scipy \
        scikit-image \
        scikit-learn \
        apex \
        wget \
        configparser \
        pycocotools==2.0.2 \
        prettytable \
        onnx \
        onnxruntime-gpu \
        pycuda \
        PyYAML \
        mlflow


#        scipy \
        #onnx \
        #apex \

WORKDIR /app
COPY datasets datasets
COPY networks networks
COPY utils utils
COPY creds.json creds.json
COPY ./dataset/cifar-10-python.tar.gz ./dataset/cifar-10-python.tar.gz

ENV LANG C.UTF-8
# port 6006 exposes tensorboard
#EXPOSE 6006 
# port 3000 exposes debugger
EXPOSE 3000

# Launch training
ENTRYPOINT ["python3", "networks/cell2d.py"]
#RUN ["/bin/bash"]
