FROM nvcr.io/nvidia/pytorch:21.12-py3-py3
LABEL maintainer="Brad Larson"

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove -y && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get install -y wget

RUN pip3 install --upgrade pip
RUN pip3 --no-cache-dir install \
        opencv-python \
        minio \
        tqdm \
        natsort \
        debugpy \
        path \
        matplotlib\
        torch \
        torchvision \
        tensorboard \
        tensorboardX \
        scipy \
        scikit-image \
        scikit-learn \
        apex \
        wget \
        configparser \
        pycocotools==2.0.2 \
        prettytable \
        onnx \
        onnxruntime-gpu \
        pycuda \
        PyYAML \
        mlflow \
        adabound



RUN echo 'alias py=python' >> ~/.bashrc

COPY README.md /app/README.md
COPY datasets /app/datasets/
COPY networks /app/networks/
COPY utils /app/utils/
COPY creds.json /app/creds.json

WORKDIR /app
ENV LANG C.UTF-8
# port 6006 exposes tensorboard
EXPOSE 6006 
# port 3000 exposes debugger
EXPOSE 3000

# Launch training
ENTRYPOINT ["python", "networks/cell2d.py"]
