FROM nvcr.io/nvidia/l4t-tensorflow:r32.5.0-tf2.3-py3
LABEL maintainer="Brad Larson"

RUN echo 'alias py=python3' >> ~/.bashrc

RUN apt-get update && apt upgrade -y && \
    apt-get install -y \
	cmake \
	libopencv-dev \
	python3-opencv \
        protobuf-compiler \
        libprotoc-dev

RUN python3 -m pip install --upgrade setuptools pip && \
    pip3 --no-cache-dir install \
        numpy \
        minio==6.0.2 \
        tqdm==4.56.0 \
        natsort==7.0.1 \
        ptvsd==4.3.2 \
        flask==1.1.2 \
        onnx \
        #nvidia-pyindex \
        #nvidia-tensorrt \ # available from nvcr.io/nvidia/l4t
        # onnxruntime==1.7.0 \
        # pycuda \ # available from nvcr.io/nvidia/l4t
        # tensorflow-addons \ # Unavaliable on ARM64
        shutils==0.1.0 \
        Jetson.GPIO

WORKDIR /app
ENV LANG C.UTF-8

# jupyter port
EXPOSE 8888 
# tensorboard port
EXPOSE 6006
# debugger port
EXPOSE 3000 
# flask port
EXPOSE 5000 

# Launch shell script
RUN ["/bin/bash"]
