# https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow/tags
FROM nvcr.io/nvidia/tensorflow:20.12-tf2-py3
LABEL maintainer="Brad Larson"

RUN echo 'alias py=python' >> ~/.bashrc

RUN apt-get update
RUN apt-get install -y libgl1-mesa-glx # for opencv-python
# RUN apt-get install -y libsm6 libxext6 ffmpeg # required by opencv-python==4.4.0.42

# numpy==1.18.5 tensorflow-gpu 2.3.0 requires numpy<1.19.0,>=1.16.0 https://github.com/tensorflow/models/issues/9200
# scipy==1.4.1 tensorflow-gpu 2.3.0 requires scipy==1.4.1
RUN pip3 install --upgrade pip
RUN pip3 --no-cache-dir install \
        opencv-python==4.4.0.42 \
        numpy==1.18.5 \ 
        scipy==1.4.1 \ 
        matplotlib==3.3.1\
        minio==6.0.0 \
        tqdm==4.48.2 \
        natsort==7.0.1 \
        ptvsd==4.3.2 \
        tifffile==2020.5.5 \
        xmltodict==0.12.0 \
        flask==1.1.2 \
        shutils==0.1.0 \
        tensorflow-model-optimization==0.4.1 \
        tf2onnx==1.6.3 \
        keras2onnx==1.7.0 \
        onnx==1.7.0 \
        pycuda==2019.1.2 \
        jupyterlab

WORKDIR /app
ENV LANG C.UTF-8

# jupyter port
EXPOSE 8888 
# tensorboard port
EXPOSE 6006
# debugger port
EXPOSE 3000 
# flask port
EXPOSE 5000 

# Launch shell script
#RUN ["/bin/bash"]
# Launch Jupyter
WORKDIR /app
ENV LANG C.UTF-8
# port 8888 exposes jupyter
EXPOSE 8888 
# port 3000 exposes debugger
#EXPOSE 3000

# Launch Jupyter
ENV NB_PREFIX /
#ENTRYPOINT [ "/usr/bin/env" ]
CMD ["bash","-c", "jupyter lab --notebook-dir=/app --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]