FROM nvcr.io/nvidia/cuda:11.4.1-cudnn8-runtime-ubuntu20.04
LABEL maintainer="Brad Larson"

# RUN apt-get install -y libsm6 libxext6 ffmpeg # required by opencv-python==4.4.0.42
RUN apt-get update -y && \
    apt-get install -y python3.8 && \
    apt-get install -y libsm6 libxext6 ffmpeg && \
    apt-get install -y wget

RUN pip3 install --upgrade pip
RUN pip3 --no-cache-dir install \
        opencv-python \
        minio==7.0.2 \
        tqdm \
        natsort \
        debugpy \
        path \
        matplotlib\
        torch \
        torchvision \
        wget \
        configparser \
        pycocotools==2.0.1 \
        prettytable \
        pycuda==2019.1.2 \
        tensorrt \
        pycuda \
        sklearn




RUN echo 'alias py=python3' >> ~/.bashrc

WORKDIR /app
ENV LANG C.UTF-8
# port 6006 exposes tensorboard
EXPOSE 6006 
# port 3000 exposes debugger
EXPOSE 3000

# Launch training
#ENTRYPOINT ["python", "segment/train.py"]
RUN ["/bin/bash"]
