apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: train
spec:
  entrypoint: train
  templates:
  - name: train
    container:
      image: localhost:32000/fcntrain:latest
      args: []