---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mldb
spec:
  storageClassName: postgresql
  capacity:
    storage: {{.Values.postgresql.size | quote}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{.Values.postgresql.hostPath.path}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. Will be used in deployment below.
  name: minio-pv-claim
  namespace: {{.Release.Namespace}}
  labels:
    app: minio-storage-claim
spec:
  # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: {{.Values.postgresql.size | quote}}
  storageClassName: postgresql

---