release: latest
server: 192.168.0.155
app: mllib

objectstore:
  name: mlstore
  apinodePort: 30990
  consolenodePort: 30991
  size: 900Gi
  image: quay.io/minio/minio:RELEASE.2021-11-24T23-19-33Z
  credentials:
    name: minio-creds
    access_key: admin
    secret_key: storeadmin
  hostPath:
    path: /nvmestore/mlstore

workflow_server:
  name: workflow-server
  nodePort: 30992
  image_workflow: quay.io/argoproj/workflow-controller:latest
  image_cli: quay.io/argoproj/argocli:latest
  image_exe: quay.io/argoproj/argoexec:latest
  s3:
    bucket: workflows
    insecure: true
workflow_metrics:
  name: workflow-controller-metrics
  nodePort: 30997
